version: '3' # (atau versi yang Anda gunakan)
services:
  web: # (atau nama service Anda)
    image: url-image-ecr-anda:latest
    ports:
      - "80:5000"
    # TAMBAHKAN BAGIAN INI:
    environment:
      - API_URL=${API_URL}
